use BD_ECCIMovies;

DROP TABLE carts_products;
DROP TABLE wishlists_products;
DROP TABLE actors_products;
DROP TABLE invoices_products;
DROP TABLE combos_products;
DROP TABLE combos;
DROP TABLE actors;
DROP TABLE historic_invoices_historic_products;
DROP TABLE historic_invoices;
DROP TABLE historic_products;
DROP TABLE invoices;
DROP TABLE carts;
DROP TABLE wishlists;
DROP TABLE valid_accounts;
DROP TABLE payment_methods;
DROP TABLE addresses;
DROP TABLE states;
DROP TABLE countries;
DROP TABLE products;
DROP TABLE subcategories;
DROP TABLE categories;
DROP TABLE users;